---
Name: nobrainerweb-blocks
After:
  - 'framework/*'
  - 'cms/*'
Before:
  - 'blocks'
---

SiteTree:
  extensions:
    - NobrainerWeb\Blocks\BlocksSiteTreeExtension

Block:
  extensions:
    - NobrainerWeb\Blocks\BlockExtension


Injector:
  BlockManager:
    class: NobrainerWeb\Blocks\BlockManager